### ISSUE TITLE
remoteItem doesn't remove items - BLOCKS CHECKOUT!

### ISSUE THREAD

**Issue by gorjan-mishevski** [mirumee/saleor-sdk#108]
Found a serious bug. The cart API remove item method doesn't remove the item, rather it only sets quantity 0.
Then when doing the checkout Saleor fails with "ZERO_QUANTITY" error.

Reproduce this by adding a product then removing the product. Observe the localstorage.

```
checkoutCreate: {,…}
checkout: null
errors: [{code: "ZERO_QUANTITY", field: "quantity", message: "The quantity should be higher than zero.",…}]
0: {code: "ZERO_QUANTITY", field: "quantity", message: "The quantity should be higher than zero.",…}
__typename: "CheckoutCreate"
```

**Comment by jwm0** [comment]
Fixed in https://github.com/mirumee/saleor-sdk/releases/tag/v0.3.0-10
