### ISSUE TITLE
window is not defined error on ssr

### ISSUE THREAD

**Issue by gmcbretas** [mirumee/saleor-sdk#44]
I'm running this sdk on NuxtJs, it's all ok when running client-side, but when I call:
"const {api, apolloClient} = await ctx.$saleorManager.connect(saleorAPI => {});" On server-side rendering, I get the "window is not defined" error.
The need of ssr is for SEO, so the search engines will index my products pages.
I thank in advance for the efforts to solve this!

**Comment by orzechdev** [comment]
Thank you for the bug report. In the last days we have fixed the missing window in https://github.com/mirumee/saleor-sdk/pull/49, and released new version already. Please check it out.
